apiVersion: v1
items:
  - apiVersion: v1
    kind: Endpoints
    metadata:
      name: metallb-webhook-service
      namespace: metallb-system
    subsets:
      - addresses:
          - ip: 10.244.101.134
            nodeName: s231226.wholesaleinternet.net
            targetRef:
              kind: Pod
              name: controller-869c4f5ccb-lgpgx
              namespace: metallb-system
              uid: 473980e4-6d40-4f13-b947-8c7f9651e7bc
        ports:
          - port: 9443
            protocol: TCP
kind: List
metadata: {}
