apiVersion: v1
items:
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    metadata:
      annotations: {}
      labels:
        app: metallb
      name: controller
      namespace: metallb-system
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: Role
      name: controller
    subjects:
      - kind: ServiceAccount
        name: controller
        namespace: metallb-system
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    metadata:
      annotations: {}
      labels:
        app: metallb
      name: pod-lister
      namespace: metallb-system
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: Role
      name: pod-lister
    subjects:
      - kind: ServiceAccount
        name: speaker
        namespace: metallb-system
kind: List
metadata: {}
