apiVersion: v1
items:
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      annotations: {}
      labels:
        app: metallb
      name: controller
      namespace: metallb-system
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: default
      namespace: metallb-system
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      annotations: {}
      labels:
        app: metallb
      name: speaker
      namespace: metallb-system
kind: List
metadata: {}
