apiVersion: v1
items:
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"RoleBinding","metadata":{"annotations":{},"labels":{"app":"metallb"},"name":"controller","namespace":"metallb-system"},"roleRef":{"apiGroup":"rbac.authorization.k8s.io","kind":"Role","name":"controller"},"subjects":[{"kind":"ServiceAccount","name":"controller","namespace":"metallb-system"}]}
    creationTimestamp: "2025-10-24T09:08:41Z"
    labels:
      app: metallb
    name: controller
    namespace: metallb-system
    resourceVersion: "44088"
    uid: bd6f9c39-c5be-41bc-a413-50a480154e7a
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: controller
  subjects:
  - kind: ServiceAccount
    name: controller
    namespace: metallb-system
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"RoleBinding","metadata":{"annotations":{},"labels":{"app":"metallb"},"name":"pod-lister","namespace":"metallb-system"},"roleRef":{"apiGroup":"rbac.authorization.k8s.io","kind":"Role","name":"pod-lister"},"subjects":[{"kind":"ServiceAccount","name":"speaker","namespace":"metallb-system"}]}
    creationTimestamp: "2025-10-24T09:08:41Z"
    labels:
      app: metallb
    name: pod-lister
    namespace: metallb-system
    resourceVersion: "44089"
    uid: 55e7bec3-2604-4e37-85f7-fe818c6728bc
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: pod-lister
  subjects:
  - kind: ServiceAccount
    name: speaker
    namespace: metallb-system
kind: List
metadata:
  resourceVersion: ""
