apiVersion: apps/v1
kind: Deployment
metadata:
  name: drone-runner
  namespace: drone
  labels:
    app.kubernetes.io/name: drone-runner
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: drone-runner
  template:
    metadata:
      labels:
        app.kubernetes.io/name: drone-runner
    spec:
      serviceAccountName: drone-runner
      containers:
        - name: runner
          image: drone/drone-runner-kube:1.0.0-rc.5
          imagePullPolicy: IfNotPresent
          env:
            # Where job pods are created by default
            - name: DRONE_NAMESPACE_DEFAULT
              value: drone
            - name: DRONE_SERVICE_ACCOUNT_DEFAULT
              value: drone-runner

            # Connect to Drone server (pick ONE option)

            # Option A: INTERNAL service (recommended inside cluster)
            - name: DRONE_RPC_HOST
              value: droneserver.drone.svc.cluster.local
            - name: DRONE_RPC_PROTO
              value: http

            # Option B: EXTERNAL via Traefik (comment A and uncomment these)
            # - name: DRONE_RPC_HOST
            #   value: drone.kwiki.it.com
            # - name: DRONE_RPC_PROTO
            #   value: https

            - name: DRONE_RPC_SECRET
              valueFrom:
                secretKeyRef:
                  name: drone-server-secret
                  key: DRONE_RPC_SECRET

            # Optional tuning / logging
            - name: DRONE_RUNNER_CAPACITY
              value: "2"
            - name: DRONE_DEBUG
              value: "true"
            - name: DRONE_TRACE
              value: "true"

          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: "1"
              memory: 1Gi
          # metrics port not required unless you scrape it
          # ports:
          #   - containerPort: 3000

