apiVersion: v1
items:
  - apiVersion: storage.k8s.io/v1
    kind: StorageClass
    metadata:
      annotations:
        storageclass.kubernetes.io/is-default-class: "false"
      name: local-path
    provisioner: rancher.io/local-path
    reclaimPolicy: Delete
    volumeBindingMode: WaitForFirstConsumer
  - allowVolumeExpansion: true
    apiVersion: storage.k8s.io/v1
    kind: StorageClass
    metadata:
      annotations:
        longhorn.io/last-applied-configmap: |
          kind: StorageClass
          apiVersion: storage.k8s.io/v1
          metadata:
            name: longhorn
            annotations:
              storageclass.kubernetes.io/is-default-class: "true"
          provisioner: driver.longhorn.io
          allowVolumeExpansion: true
          reclaimPolicy: "Delete"
          volumeBindingMode: Immediate
          parameters:
            numberOfReplicas: "3"
            staleReplicaTimeout: "30"
            fromBackup: ""
            fsType: "ext4"
            dataLocality: "disabled"
            unmapMarkSnapChainRemoved: "ignored"
            disableRevisionCounter: "true"
            dataEngine: "v1"
            backupTargetName: "default"
        storageclass.kubernetes.io/is-default-class: "true"
      name: longhorn
    parameters:
      backupTargetName: default
      dataEngine: v1
      dataLocality: disabled
      disableRevisionCounter: "true"
      fromBackup: ""
      fsType: ext4
      numberOfReplicas: "3"
      staleReplicaTimeout: "30"
      unmapMarkSnapChainRemoved: ignored
    provisioner: driver.longhorn.io
    reclaimPolicy: Delete
    volumeBindingMode: Immediate
  - allowVolumeExpansion: true
    apiVersion: storage.k8s.io/v1
    kind: StorageClass
    metadata:
      name: longhorn-static
    parameters:
      staleReplicaTimeout: "30"
    provisioner: driver.longhorn.io
    reclaimPolicy: Delete
    volumeBindingMode: Immediate
kind: List
metadata: {}
