apiVersion: v1
kind: Pod
metadata:
  name: iperf-client
spec:
  containers:
  - name: iperf-client
    image: networkstatic/iperf3
    command: ["iperf3", "-c", "10.244.101.136", "-t", "20"]
  restartPolicy: Never
  nodeSelector:
    kubernetes.io/hostname: hcp.kwiki.it.com

