apiVersion: v1
kind: Pod
metadata:
  name: iperf-server
  labels:
    app: iperf
spec:
  containers:
  - name: iperf-server
    image: networkstatic/iperf3
    command: ["iperf3", "-s"]
    ports:
    - containerPort: 5201
  nodeSelector:
    kubernetes.io/hostname: s231226.wholesaleinternet.net

