apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: external-dns
spec:
  chart:
    spec:
      chart: external-dns
      interval: 12h
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
      version: 1.21.1
  interval: 30m
  timeout: 5m
  values:
    domainFilters:
      - xn--cyberlnx-ykb.com
      - getuntoldstory.com
      - processlayerai.com
    env:
      - name: CF_API_TOKEN
        valueFrom:
          secretKeyRef:
            key: api-token
            name: cloudflare-api-token
    extraArgs:
      - --cloudflare-dns-records-per-page=5000
    nodeSelector:
      platform.cyberlynx.io/control-workloads: "true"
    policy: upsert-only
    provider:
      name: cloudflare
    registry: txt
    sources:
      - ingress
      - traefik-proxy
    txtOwnerId: kubernetes-production
