apiVersion: v1
items:
  - apiVersion: v1
    kind: Pod
    metadata:
      annotations:
        cni.projectcalico.org/containerID: 2db70a11068f10d652b88fbe40f0c38226ead0d7acb11f9a25bbf072e4606817
        cni.projectcalico.org/podIP: 10.244.101.137/32
        cni.projectcalico.org/podIPs: 10.244.101.137/32
        kubectl.kubernetes.io/restartedAt: "2026-02-08T15:16:25Z"
      generateName: cyberlynx-blog-659dc45d4f-
      labels:
        app.kubernetes.io/name: cyberlynx-blog
        pod-template-hash: 659dc45d4f
      name: cyberlynx-blog-659dc45d4f-bvqh4
      namespace: websites
      ownerReferences:
        - apiVersion: apps/v1
          blockOwnerDeletion: true
          controller: true
          kind: ReplicaSet
          name: cyberlynx-blog-659dc45d4f
          uid: affaac0f-f30e-45d5-9c78-4eafe4fb7525
    spec:
      containers:
        - env:
            - name: NODE_ENV
              value: production
            - name: PORT
              value: "8080"
          envFrom:
            - secretRef:
                name: cyberlynx-blog-env
          image: cyberlynxx/cyberlynx-blog:e2c3b81
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: http
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 20
            successThreshold: 1
            timeoutSeconds: 1
          name: web
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: http
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              cpu: 250m
              memory: 256Mi
            requests:
              cpu: 50m
              memory: 64Mi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsGroup: 1001
            runAsUser: 1001
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
              name: kube-api-access-c9vch
              readOnly: true
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      imagePullSecrets:
        - name: dockerhub-creds
      nodeName: s231226.wholesaleinternet.net
      preemptionPolicy: PreemptLowerPriority
      priority: 0
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 2000
        runAsNonRoot: true
      serviceAccount: default
      serviceAccountName: default
      terminationGracePeriodSeconds: 30
      tolerations:
        - effect: NoExecute
          key: node.kubernetes.io/not-ready
          operator: Exists
          tolerationSeconds: 300
        - effect: NoExecute
          key: node.kubernetes.io/unreachable
          operator: Exists
          tolerationSeconds: 300
      volumes:
        - name: kube-api-access-c9vch
          projected:
            defaultMode: 420
            sources:
              - serviceAccountToken:
                  expirationSeconds: 3607
                  path: token
              - configMap:
                  items:
                    - key: ca.crt
                      path: ca.crt
                  name: kube-root-ca.crt
              - downwardAPI:
                  items:
                    - fieldRef:
                        apiVersion: v1
                        fieldPath: metadata.namespace
                      path: namespace
  - apiVersion: v1
    kind: Service
    metadata:
      annotations: {}
      labels:
        app.kubernetes.io/name: cyberlynx-blog
      name: cyberlynx-blog
      namespace: websites
    spec:
      clusterIP: 10.96.149.201
      clusterIPs:
        - 10.96.149.201
      internalTrafficPolicy: Cluster
      ipFamilies:
        - IPv4
      ipFamilyPolicy: SingleStack
      ports:
        - name: http
          port: 80
          protocol: TCP
          targetPort: 8080
      selector:
        app.kubernetes.io/name: cyberlynx-blog
      sessionAffinity: None
      type: ClusterIP
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      annotations:
        deployment.kubernetes.io/revision: "10"
      labels:
        app.kubernetes.io/name: cyberlynx-blog
        app.kubernetes.io/part-of: cyberlynx
      name: cyberlynx-blog
      namespace: websites
    spec:
      progressDeadlineSeconds: 600
      replicas: 1
      revisionHistoryLimit: 3
      selector:
        matchLabels:
          app.kubernetes.io/name: cyberlynx-blog
      strategy:
        rollingUpdate:
          maxSurge: 1
          maxUnavailable: 0
        type: RollingUpdate
      template:
        metadata:
          annotations:
            kubectl.kubernetes.io/restartedAt: "2026-02-08T15:16:25Z"
          creationTimestamp: null
          labels:
            app.kubernetes.io/name: cyberlynx-blog
        spec:
          containers:
            - env:
                - name: NODE_ENV
                  value: production
                - name: PORT
                  value: "8080"
              envFrom:
                - secretRef:
                    name: cyberlynx-blog-env
              image: cyberlynxx/cyberlynx-blog:e2c3b81
              imagePullPolicy: IfNotPresent
              livenessProbe:
                failureThreshold: 3
                httpGet:
                  path: /
                  port: http
                  scheme: HTTP
                initialDelaySeconds: 15
                periodSeconds: 20
                successThreshold: 1
                timeoutSeconds: 1
              name: web
              ports:
                - containerPort: 8080
                  name: http
                  protocol: TCP
              readinessProbe:
                failureThreshold: 3
                httpGet:
                  path: /
                  port: http
                  scheme: HTTP
                initialDelaySeconds: 5
                periodSeconds: 10
                successThreshold: 1
                timeoutSeconds: 1
              resources:
                limits:
                  cpu: 250m
                  memory: 256Mi
                requests:
                  cpu: 50m
                  memory: 64Mi
              securityContext:
                allowPrivilegeEscalation: false
                readOnlyRootFilesystem: true
                runAsGroup: 1001
                runAsUser: 1001
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          imagePullSecrets:
            - name: dockerhub-creds
          restartPolicy: Always
          schedulerName: default-scheduler
          securityContext:
            fsGroup: 2000
            runAsNonRoot: true
          terminationGracePeriodSeconds: 30
  - apiVersion: apps/v1
    kind: ReplicaSet
    metadata:
      annotations:
        deployment.kubernetes.io/desired-replicas: "1"
        deployment.kubernetes.io/max-replicas: "2"
        deployment.kubernetes.io/revision: "10"
      labels:
        app.kubernetes.io/name: cyberlynx-blog
        pod-template-hash: 659dc45d4f
      name: cyberlynx-blog-659dc45d4f
      namespace: websites
      ownerReferences:
        - apiVersion: apps/v1
          blockOwnerDeletion: true
          controller: true
          kind: Deployment
          name: cyberlynx-blog
          uid: 031bd32f-d9bf-440f-8c0f-0dafb8352220
    spec:
      replicas: 1
      selector:
        matchLabels:
          app.kubernetes.io/name: cyberlynx-blog
          pod-template-hash: 659dc45d4f
      template:
        metadata:
          annotations:
            kubectl.kubernetes.io/restartedAt: "2026-02-08T15:16:25Z"
          creationTimestamp: null
          labels:
            app.kubernetes.io/name: cyberlynx-blog
            pod-template-hash: 659dc45d4f
        spec:
          containers:
            - env:
                - name: NODE_ENV
                  value: production
                - name: PORT
                  value: "8080"
              envFrom:
                - secretRef:
                    name: cyberlynx-blog-env
              image: cyberlynxx/cyberlynx-blog:e2c3b81
              imagePullPolicy: IfNotPresent
              livenessProbe:
                failureThreshold: 3
                httpGet:
                  path: /
                  port: http
                  scheme: HTTP
                initialDelaySeconds: 15
                periodSeconds: 20
                successThreshold: 1
                timeoutSeconds: 1
              name: web
              ports:
                - containerPort: 8080
                  name: http
                  protocol: TCP
              readinessProbe:
                failureThreshold: 3
                httpGet:
                  path: /
                  port: http
                  scheme: HTTP
                initialDelaySeconds: 5
                periodSeconds: 10
                successThreshold: 1
                timeoutSeconds: 1
              resources:
                limits:
                  cpu: 250m
                  memory: 256Mi
                requests:
                  cpu: 50m
                  memory: 64Mi
              securityContext:
                allowPrivilegeEscalation: false
                readOnlyRootFilesystem: true
                runAsGroup: 1001
                runAsUser: 1001
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          imagePullSecrets:
            - name: dockerhub-creds
          restartPolicy: Always
          schedulerName: default-scheduler
          securityContext:
            fsGroup: 2000
            runAsNonRoot: true
          terminationGracePeriodSeconds: 30
  - apiVersion: apps/v1
    kind: ReplicaSet
    metadata:
      annotations:
        deployment.kubernetes.io/desired-replicas: "1"
        deployment.kubernetes.io/max-replicas: "2"
        deployment.kubernetes.io/revision: "7"
      labels:
        app.kubernetes.io/name: cyberlynx-blog
        pod-template-hash: 65cb8cbc44
      name: cyberlynx-blog-65cb8cbc44
      namespace: websites
      ownerReferences:
        - apiVersion: apps/v1
          blockOwnerDeletion: true
          controller: true
          kind: Deployment
          name: cyberlynx-blog
          uid: 031bd32f-d9bf-440f-8c0f-0dafb8352220
    spec:
      replicas: 0
      selector:
        matchLabels:
          app.kubernetes.io/name: cyberlynx-blog
          pod-template-hash: 65cb8cbc44
      template:
        metadata:
          annotations:
            kubectl.kubernetes.io/restartedAt: "2026-02-08T15:13:12Z"
          creationTimestamp: null
          labels:
            app.kubernetes.io/name: cyberlynx-blog
            pod-template-hash: 65cb8cbc44
        spec:
          containers:
            - env:
                - name: NODE_ENV
                  value: production
                - name: PORT
                  value: "8080"
              envFrom:
                - secretRef:
                    name: cyberlynx-blog-env
              image: cyberlynxx/cyberlynx-blog:e4b31ef
              imagePullPolicy: IfNotPresent
              livenessProbe:
                failureThreshold: 3
                httpGet:
                  path: /
                  port: http
                  scheme: HTTP
                initialDelaySeconds: 15
                periodSeconds: 20
                successThreshold: 1
                timeoutSeconds: 1
              name: web
              ports:
                - containerPort: 8080
                  name: http
                  protocol: TCP
              readinessProbe:
                failureThreshold: 3
                httpGet:
                  path: /
                  port: http
                  scheme: HTTP
                initialDelaySeconds: 5
                periodSeconds: 10
                successThreshold: 1
                timeoutSeconds: 1
              resources:
                limits:
                  cpu: 250m
                  memory: 256Mi
                requests:
                  cpu: 50m
                  memory: 64Mi
              securityContext:
                allowPrivilegeEscalation: false
                readOnlyRootFilesystem: true
                runAsGroup: 1001
                runAsUser: 1001
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          imagePullSecrets:
            - name: dockerhub-creds
          restartPolicy: Always
          schedulerName: default-scheduler
          securityContext:
            fsGroup: 2000
            runAsNonRoot: true
          terminationGracePeriodSeconds: 30
  - apiVersion: apps/v1
    kind: ReplicaSet
    metadata:
      annotations:
        deployment.kubernetes.io/desired-replicas: "1"
        deployment.kubernetes.io/max-replicas: "2"
        deployment.kubernetes.io/revision: "9"
      labels:
        app.kubernetes.io/name: cyberlynx-blog
        pod-template-hash: 76b4f9447
      name: cyberlynx-blog-76b4f9447
      namespace: websites
      ownerReferences:
        - apiVersion: apps/v1
          blockOwnerDeletion: true
          controller: true
          kind: Deployment
          name: cyberlynx-blog
          uid: 031bd32f-d9bf-440f-8c0f-0dafb8352220
    spec:
      replicas: 0
      selector:
        matchLabels:
          app.kubernetes.io/name: cyberlynx-blog
          pod-template-hash: 76b4f9447
      template:
        metadata:
          annotations:
            kubectl.kubernetes.io/restartedAt: "2026-02-08T15:16:25Z"
          creationTimestamp: null
          labels:
            app.kubernetes.io/name: cyberlynx-blog
            pod-template-hash: 76b4f9447
        spec:
          containers:
            - env:
                - name: NODE_ENV
                  value: production
                - name: PORT
                  value: "8080"
              envFrom:
                - secretRef:
                    name: cyberlynx-blog-env
              image: cyberlynxx/cyberlynx-blog:7c538ea
              imagePullPolicy: IfNotPresent
              livenessProbe:
                failureThreshold: 3
                httpGet:
                  path: /
                  port: http
                  scheme: HTTP
                initialDelaySeconds: 15
                periodSeconds: 20
                successThreshold: 1
                timeoutSeconds: 1
              name: web
              ports:
                - containerPort: 8080
                  name: http
                  protocol: TCP
              readinessProbe:
                failureThreshold: 3
                httpGet:
                  path: /
                  port: http
                  scheme: HTTP
                initialDelaySeconds: 5
                periodSeconds: 10
                successThreshold: 1
                timeoutSeconds: 1
              resources:
                limits:
                  cpu: 250m
                  memory: 256Mi
                requests:
                  cpu: 50m
                  memory: 64Mi
              securityContext:
                allowPrivilegeEscalation: false
                readOnlyRootFilesystem: true
                runAsGroup: 1001
                runAsUser: 1001
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          imagePullSecrets:
            - name: dockerhub-creds
          restartPolicy: Always
          schedulerName: default-scheduler
          securityContext:
            fsGroup: 2000
            runAsNonRoot: true
          terminationGracePeriodSeconds: 30
  - apiVersion: apps/v1
    kind: ReplicaSet
    metadata:
      annotations:
        deployment.kubernetes.io/desired-replicas: "1"
        deployment.kubernetes.io/max-replicas: "2"
        deployment.kubernetes.io/revision: "8"
      labels:
        app.kubernetes.io/name: cyberlynx-blog
        pod-template-hash: b85c5d96f
      name: cyberlynx-blog-b85c5d96f
      namespace: websites
      ownerReferences:
        - apiVersion: apps/v1
          blockOwnerDeletion: true
          controller: true
          kind: Deployment
          name: cyberlynx-blog
          uid: 031bd32f-d9bf-440f-8c0f-0dafb8352220
    spec:
      replicas: 0
      selector:
        matchLabels:
          app.kubernetes.io/name: cyberlynx-blog
          pod-template-hash: b85c5d96f
      template:
        metadata:
          annotations:
            kubectl.kubernetes.io/restartedAt: "2026-02-08T15:16:25Z"
          creationTimestamp: null
          labels:
            app.kubernetes.io/name: cyberlynx-blog
            pod-template-hash: b85c5d96f
        spec:
          containers:
            - env:
                - name: NODE_ENV
                  value: production
                - name: PORT
                  value: "8080"
              envFrom:
                - secretRef:
                    name: cyberlynx-blog-env
              image: cyberlynxx/cyberlynx-blog:e4b31ef
              imagePullPolicy: IfNotPresent
              livenessProbe:
                failureThreshold: 3
                httpGet:
                  path: /
                  port: http
                  scheme: HTTP
                initialDelaySeconds: 15
                periodSeconds: 20
                successThreshold: 1
                timeoutSeconds: 1
              name: web
              ports:
                - containerPort: 8080
                  name: http
                  protocol: TCP
              readinessProbe:
                failureThreshold: 3
                httpGet:
                  path: /
                  port: http
                  scheme: HTTP
                initialDelaySeconds: 5
                periodSeconds: 10
                successThreshold: 1
                timeoutSeconds: 1
              resources:
                limits:
                  cpu: 250m
                  memory: 256Mi
                requests:
                  cpu: 50m
                  memory: 64Mi
              securityContext:
                allowPrivilegeEscalation: false
                readOnlyRootFilesystem: true
                runAsGroup: 1001
                runAsUser: 1001
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          imagePullSecrets:
            - name: dockerhub-creds
          restartPolicy: Always
          schedulerName: default-scheduler
          securityContext:
            fsGroup: 2000
            runAsNonRoot: true
          terminationGracePeriodSeconds: 30
kind: List
metadata: {}
