apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: kwiki
  namespace: flux-system
spec:
  interval: 5m
  url: https://github.com/TheDivine/kwiki.git
  ref:
    branch: main
