apiVersion: v1
items:
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"RoleBinding","metadata":{"annotations":{},"name":"local-path-provisioner-bind","namespace":"local-path-storage"},"roleRef":{"apiGroup":"rbac.authorization.k8s.io","kind":"Role","name":"local-path-provisioner-role"},"subjects":[{"kind":"ServiceAccount","name":"local-path-provisioner-service-account","namespace":"local-path-storage"}]}
    creationTimestamp: "2025-11-19T16:22:15Z"
    name: local-path-provisioner-bind
    namespace: local-path-storage
    resourceVersion: "3242064"
    uid: 6e523da8-a0b0-40aa-8f29-83f4ad97eeec
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: local-path-provisioner-role
  subjects:
  - kind: ServiceAccount
    name: local-path-provisioner-service-account
    namespace: local-path-storage
kind: List
metadata:
  resourceVersion: ""
