apiVersion: v1
items:
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"Role","metadata":{"annotations":{},"name":"local-path-provisioner-role","namespace":"local-path-storage"},"rules":[{"apiGroups":[""],"resources":["pods"],"verbs":["get","list","watch","create","patch","update","delete"]}]}
    creationTimestamp: "2025-11-19T16:22:15Z"
    name: local-path-provisioner-role
    namespace: local-path-storage
    resourceVersion: "3242062"
    uid: 4018c026-954a-4ef6-8f5c-61aaff6012ef
  rules:
  - apiGroups:
    - ""
    resources:
    - pods
    verbs:
    - get
    - list
    - watch
    - create
    - patch
    - update
    - delete
kind: List
metadata:
  resourceVersion: ""
