apiVersion: v1
items:
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    metadata:
      annotations: {}
      labels:
        app.kubernetes.io/component: awx
        app.kubernetes.io/managed-by: awx-operator
        app.kubernetes.io/operator-version: 2.19.1
        app.kubernetes.io/part-of: awx-kwiki
      name: awx-kwiki
      namespace: awx
      ownerReferences:
        - apiVersion: awx.ansible.com/v1beta1
          kind: AWX
          name: awx-kwiki
          uid: 0c76c8fc-9e96-4ff7-8b6c-9aac9fabce91
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: Role
      name: awx-kwiki
    subjects:
      - kind: ServiceAccount
        name: awx-kwiki
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    metadata:
      annotations: {}
      name: awx-operator-awx-manager-rolebinding
      namespace: awx
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: Role
      name: awx-operator-awx-manager-role
    subjects:
      - kind: ServiceAccount
        name: awx-operator-controller-manager
        namespace: awx
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    metadata:
      annotations: {}
      name: awx-operator-leader-election-rolebinding
      namespace: awx
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: Role
      name: awx-operator-leader-election-role
    subjects:
      - kind: ServiceAccount
        name: awx-operator-controller-manager
        namespace: awx
kind: List
metadata: {}
