apiVersion: v1
items:
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      annotations: {}
      labels:
        app.kubernetes.io/component: awx
        app.kubernetes.io/managed-by: awx-operator
        app.kubernetes.io/operator-version: 2.19.1
        app.kubernetes.io/part-of: awx-kwiki
      name: awx-kwiki
      namespace: awx
      ownerReferences:
        - apiVersion: awx.ansible.com/v1beta1
          kind: AWX
          name: awx-kwiki
          uid: 0c76c8fc-9e96-4ff7-8b6c-9aac9fabce91
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      annotations: {}
      name: awx-operator-controller-manager
      namespace: awx
  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: default
      namespace: awx
kind: List
metadata: {}
