apiVersion: v1
items:
- apiVersion: batch/v1
  kind: Job
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: '{"apiVersion":"batch/v1","kind":"Job","metadata":{"labels":{"app.kubernetes.io/component":"awx","app.kubernetes.io/managed-by":"awx-operator","app.kubernetes.io/operator-version":"2.19.1","app.kubernetes.io/part-of":"awx-kwiki","app.kubernetes.io/version":"24.6.1"},"name":"awx-kwiki-migration-24.6.1","namespace":"awx"},"spec":{"template":{"metadata":{"labels":{"app.kubernetes.io/component":"awx","app.kubernetes.io/managed-by":"awx-operator","app.kubernetes.io/operator-version":"2.19.1","app.kubernetes.io/part-of":"awx-kwiki","app.kubernetes.io/version":"24.6.1"}},"spec":{"containers":[{"command":["awx-manage","migrate","--noinput"],"image":"quay.io/ansible/awx:24.6.1","name":"migration-job","volumeMounts":[{"mountPath":"/etc/tower/conf.d/credentials.py","name":"awx-kwiki-application-credentials","readOnly":true,"subPath":"credentials.py"},{"mountPath":"/etc/tower/SECRET_KEY","name":"awx-kwiki-secret-key","readOnly":true,"subPath":"SECRET_KEY"},{"mountPath":"/etc/tower/settings.py","name":"awx-kwiki-settings","readOnly":true,"subPath":"settings.py"}]}],"dnsPolicy":"ClusterFirst","nodeSelector":{"awx-node":"arm"},"restartPolicy":"Never","serviceAccountName":"awx-kwiki","terminationGracePeriodSeconds":30,"volumes":[{"name":"awx-kwiki-application-credentials","secret":{"items":[{"key":"credentials.py","path":"credentials.py"},{"key":"ldap.py","path":"ldap.py"},{"key":"execution_environments.py","path":"execution_environments.py"}],"secretName":"awx-kwiki-app-credentials"}},{"name":"awx-kwiki-secret-key","secret":{"items":[{"key":"secret_key","path":"SECRET_KEY"}],"secretName":"awx-kwiki-secret-key"}},{"configMap":{"items":[{"key":"settings","path":"settings.py"}],"name":"awx-kwiki-awx-configmap"},"name":"awx-kwiki-settings"}]}}}}'
    creationTimestamp: "2025-11-19T17:13:43Z"
    generation: 1
    labels:
      app.kubernetes.io/component: awx
      app.kubernetes.io/managed-by: awx-operator
      app.kubernetes.io/operator-version: 2.19.1
      app.kubernetes.io/part-of: awx-kwiki
      app.kubernetes.io/version: 24.6.1
    name: awx-kwiki-migration-24.6.1
    namespace: awx
    ownerReferences:
    - apiVersion: awx.ansible.com/v1beta1
      kind: AWX
      name: awx-kwiki
      uid: 0c76c8fc-9e96-4ff7-8b6c-9aac9fabce91
    resourceVersion: "3249240"
    uid: f8f7a65f-a44b-490f-9ab2-7f82d7a59367
  spec:
    backoffLimit: 6
    completionMode: NonIndexed
    completions: 1
    manualSelector: false
    parallelism: 1
    podReplacementPolicy: TerminatingOrFailed
    selector:
      matchLabels:
        batch.kubernetes.io/controller-uid: f8f7a65f-a44b-490f-9ab2-7f82d7a59367
    suspend: false
    template:
      metadata:
        creationTimestamp: null
        labels:
          app.kubernetes.io/component: awx
          app.kubernetes.io/managed-by: awx-operator
          app.kubernetes.io/operator-version: 2.19.1
          app.kubernetes.io/part-of: awx-kwiki
          app.kubernetes.io/version: 24.6.1
          batch.kubernetes.io/controller-uid: f8f7a65f-a44b-490f-9ab2-7f82d7a59367
          batch.kubernetes.io/job-name: awx-kwiki-migration-24.6.1
          controller-uid: f8f7a65f-a44b-490f-9ab2-7f82d7a59367
          job-name: awx-kwiki-migration-24.6.1
      spec:
        containers:
        - command:
          - awx-manage
          - migrate
          - --noinput
          image: quay.io/ansible/awx:24.6.1
          imagePullPolicy: IfNotPresent
          name: migration-job
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /etc/tower/conf.d/credentials.py
            name: awx-kwiki-application-credentials
            readOnly: true
            subPath: credentials.py
          - mountPath: /etc/tower/SECRET_KEY
            name: awx-kwiki-secret-key
            readOnly: true
            subPath: SECRET_KEY
          - mountPath: /etc/tower/settings.py
            name: awx-kwiki-settings
            readOnly: true
            subPath: settings.py
        dnsPolicy: ClusterFirst
        nodeSelector:
          awx-node: arm
        restartPolicy: Never
        schedulerName: default-scheduler
        securityContext: {}
        serviceAccount: awx-kwiki
        serviceAccountName: awx-kwiki
        terminationGracePeriodSeconds: 30
        volumes:
        - name: awx-kwiki-application-credentials
          secret:
            defaultMode: 420
            items:
            - key: credentials.py
              path: credentials.py
            - key: ldap.py
              path: ldap.py
            - key: execution_environments.py
              path: execution_environments.py
            secretName: awx-kwiki-app-credentials
        - name: awx-kwiki-secret-key
          secret:
            defaultMode: 420
            items:
            - key: secret_key
              path: SECRET_KEY
            secretName: awx-kwiki-secret-key
        - configMap:
            defaultMode: 420
            items:
            - key: settings
              path: settings.py
            name: awx-kwiki-awx-configmap
          name: awx-kwiki-settings
  status:
    completionTime: "2025-11-19T17:16:38Z"
    conditions:
    - lastProbeTime: "2025-11-19T17:16:38Z"
      lastTransitionTime: "2025-11-19T17:16:38Z"
      message: Reached expected number of succeeded pods
      reason: CompletionsReached
      status: "True"
      type: SuccessCriteriaMet
    - lastProbeTime: "2025-11-19T17:16:38Z"
      lastTransitionTime: "2025-11-19T17:16:38Z"
      message: Reached expected number of succeeded pods
      reason: CompletionsReached
      status: "True"
      type: Complete
    ready: 0
    startTime: "2025-11-19T17:13:43Z"
    succeeded: 1
    terminating: 0
    uncountedTerminatedPods: {}
kind: List
metadata:
  resourceVersion: ""
