apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: rancher.io/local-path
      volume.kubernetes.io/selected-node: hcp.kwiki.it.com
      volume.kubernetes.io/storage-provisioner: rancher.io/local-path
    creationTimestamp: "2025-11-19T16:58:34Z"
    finalizers:
    - kubernetes.io/pvc-protection
    labels:
      app.kubernetes.io/component: database
      app.kubernetes.io/instance: postgres-15-awx-kwiki
      app.kubernetes.io/managed-by: awx-operator
      app.kubernetes.io/name: postgres-15
    name: postgres-15-awx-kwiki-postgres-15-0
    namespace: awx
    resourceVersion: "3246556"
    uid: 2c0a9192-6f2c-4e64-9be7-372eb47f7ba3
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 8Gi
    storageClassName: local-path
    volumeMode: Filesystem
    volumeName: pvc-2c0a9192-6f2c-4e64-9be7-372eb47f7ba3
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 8Gi
    phase: Bound
kind: List
metadata:
  resourceVersion: ""
