apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: platform-secrets
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: cloudflare-api-token
  data:
    - secretKey: api-token
      remoteRef:
        key: production/cloudflare/api-token
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-api-token
  namespace: external-dns
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: platform-secrets
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: cloudflare-api-token
  data:
    - secretKey: api-token
      remoteRef:
        key: production/cloudflare/api-token
