apiVersion: v1
items:
- apiVersion: policy/v1
  kind: PodDisruptionBudget
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"policy/v1","kind":"PodDisruptionBudget","metadata":{"annotations":{},"labels":{"k8s-app":"calico-kube-controllers"},"name":"calico-kube-controllers","namespace":"kube-system"},"spec":{"maxUnavailable":1,"selector":{"matchLabels":{"k8s-app":"calico-kube-controllers"}}}}
    creationTimestamp: "2025-10-24T01:13:57Z"
    generation: 1
    labels:
      k8s-app: calico-kube-controllers
    name: calico-kube-controllers
    namespace: kube-system
    resourceVersion: "22604195"
    uid: 64eb99ee-0754-437e-97fd-ae4d79b77de7
  spec:
    maxUnavailable: 1
    selector:
      matchLabels:
        k8s-app: calico-kube-controllers
  status:
    conditions:
    - lastTransitionTime: "2026-02-08T14:15:03Z"
      message: ""
      observedGeneration: 1
      reason: SufficientPods
      status: "True"
      type: DisruptionAllowed
    currentHealthy: 1
    desiredHealthy: 0
    disruptionsAllowed: 1
    expectedPods: 1
    observedGeneration: 1
kind: List
metadata:
  resourceVersion: ""
