apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-data
  namespace: backup
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: longhorn
