apiVersion: v1
items:
  - apiVersion: v1
    kind: Pod
    metadata:
      annotations:
        cni.projectcalico.org/containerID: e05bea6486a1beaaec7539c7f564446a923db7433251133fd1e224244e00ae58
        cni.projectcalico.org/podIP: 10.244.91.219/32
        cni.projectcalico.org/podIPs: 10.244.91.219/32
      generateName: local-path-provisioner-7f57b55d56-
      labels:
        app: local-path-provisioner
        pod-template-hash: 7f57b55d56
      name: local-path-provisioner-7f57b55d56-8lm9q
      namespace: local-path-storage
      ownerReferences:
        - apiVersion: apps/v1
          blockOwnerDeletion: true
          controller: true
          kind: ReplicaSet
          name: local-path-provisioner-7f57b55d56
          uid: 117ee9b8-805e-41d9-a278-86ff5f2f717e
    spec:
      containers:
        - command:
            - local-path-provisioner
            - --debug
            - start
            - --config
            - /etc/config/config.json
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: CONFIG_MOUNT_PATH
              value: /etc/config/
          image: rancher/local-path-provisioner:v0.0.32
          imagePullPolicy: IfNotPresent
          name: local-path-provisioner
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /etc/config/
              name: config-volume
            - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
              name: kube-api-access-wwx5f
              readOnly: true
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      nodeName: hcp.kwiki.it.com
      preemptionPolicy: PreemptLowerPriority
      priority: 0
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: local-path-provisioner-service-account
      serviceAccountName: local-path-provisioner-service-account
      terminationGracePeriodSeconds: 30
      tolerations:
        - effect: NoExecute
          key: node.kubernetes.io/not-ready
          operator: Exists
          tolerationSeconds: 300
        - effect: NoExecute
          key: node.kubernetes.io/unreachable
          operator: Exists
          tolerationSeconds: 300
      volumes:
        - configMap:
            defaultMode: 420
            name: local-path-config
          name: config-volume
        - name: kube-api-access-wwx5f
          projected:
            defaultMode: 420
            sources:
              - serviceAccountToken:
                  expirationSeconds: 3607
                  path: token
              - configMap:
                  items:
                    - key: ca.crt
                      path: ca.crt
                  name: kube-root-ca.crt
              - downwardAPI:
                  items:
                    - fieldRef:
                        apiVersion: v1
                        fieldPath: metadata.namespace
                      path: namespace
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      annotations:
        deployment.kubernetes.io/revision: "1"
      name: local-path-provisioner
      namespace: local-path-storage
    spec:
      progressDeadlineSeconds: 600
      replicas: 1
      revisionHistoryLimit: 10
      selector:
        matchLabels:
          app: local-path-provisioner
      strategy:
        rollingUpdate:
          maxSurge: 25%
          maxUnavailable: 25%
        type: RollingUpdate
      template:
        metadata:
          creationTimestamp: null
          labels:
            app: local-path-provisioner
        spec:
          containers:
            - command:
                - local-path-provisioner
                - --debug
                - start
                - --config
                - /etc/config/config.json
              env:
                - name: POD_NAMESPACE
                  valueFrom:
                    fieldRef:
                      apiVersion: v1
                      fieldPath: metadata.namespace
                - name: CONFIG_MOUNT_PATH
                  value: /etc/config/
              image: rancher/local-path-provisioner:v0.0.32
              imagePullPolicy: IfNotPresent
              name: local-path-provisioner
              resources: {}
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              volumeMounts:
                - mountPath: /etc/config/
                  name: config-volume
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          schedulerName: default-scheduler
          securityContext: {}
          serviceAccount: local-path-provisioner-service-account
          serviceAccountName: local-path-provisioner-service-account
          terminationGracePeriodSeconds: 30
          volumes:
            - configMap:
                defaultMode: 420
                name: local-path-config
              name: config-volume
  - apiVersion: apps/v1
    kind: ReplicaSet
    metadata:
      annotations:
        deployment.kubernetes.io/desired-replicas: "1"
        deployment.kubernetes.io/max-replicas: "2"
        deployment.kubernetes.io/revision: "1"
      labels:
        app: local-path-provisioner
        pod-template-hash: 7f57b55d56
      name: local-path-provisioner-7f57b55d56
      namespace: local-path-storage
      ownerReferences:
        - apiVersion: apps/v1
          blockOwnerDeletion: true
          controller: true
          kind: Deployment
          name: local-path-provisioner
          uid: 87ea92ab-0521-410d-af28-50ae9009ab8b
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: local-path-provisioner
          pod-template-hash: 7f57b55d56
      template:
        metadata:
          creationTimestamp: null
          labels:
            app: local-path-provisioner
            pod-template-hash: 7f57b55d56
        spec:
          containers:
            - command:
                - local-path-provisioner
                - --debug
                - start
                - --config
                - /etc/config/config.json
              env:
                - name: POD_NAMESPACE
                  valueFrom:
                    fieldRef:
                      apiVersion: v1
                      fieldPath: metadata.namespace
                - name: CONFIG_MOUNT_PATH
                  value: /etc/config/
              image: rancher/local-path-provisioner:v0.0.32
              imagePullPolicy: IfNotPresent
              name: local-path-provisioner
              resources: {}
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              volumeMounts:
                - mountPath: /etc/config/
                  name: config-volume
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          schedulerName: default-scheduler
          securityContext: {}
          serviceAccount: local-path-provisioner-service-account
          serviceAccountName: local-path-provisioner-service-account
          terminationGracePeriodSeconds: 30
          volumes:
            - configMap:
                defaultMode: 420
                name: local-path-config
              name: config-volume
kind: List
metadata: {}
