apiVersion: v1
items:
- apiVersion: storage.k8s.io/v1
  kind: StorageClass
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"storage.k8s.io/v1","kind":"StorageClass","metadata":{"annotations":{},"name":"local-path"},"provisioner":"rancher.io/local-path","reclaimPolicy":"Delete","volumeBindingMode":"WaitForFirstConsumer"}
      storageclass.kubernetes.io/is-default-class: "false"
    creationTimestamp: "2025-11-19T16:22:15Z"
    name: local-path
    resourceVersion: "3368012"
    uid: e658e1e9-fa0b-483c-8c81-ff032b229be9
  provisioner: rancher.io/local-path
  reclaimPolicy: Delete
  volumeBindingMode: WaitForFirstConsumer
- allowVolumeExpansion: true
  apiVersion: storage.k8s.io/v1
  kind: StorageClass
  metadata:
    annotations:
      longhorn.io/last-applied-configmap: |
        kind: StorageClass
        apiVersion: storage.k8s.io/v1
        metadata:
          name: longhorn
          annotations:
            storageclass.kubernetes.io/is-default-class: "true"
        provisioner: driver.longhorn.io
        allowVolumeExpansion: true
        reclaimPolicy: "Delete"
        volumeBindingMode: Immediate
        parameters:
          numberOfReplicas: "3"
          staleReplicaTimeout: "30"
          fromBackup: ""
          fsType: "ext4"
          dataLocality: "disabled"
          unmapMarkSnapChainRemoved: "ignored"
          disableRevisionCounter: "true"
          dataEngine: "v1"
          backupTargetName: "default"
      storageclass.kubernetes.io/is-default-class: "true"
    creationTimestamp: "2025-11-20T10:29:29Z"
    name: longhorn
    resourceVersion: "3366103"
    uid: 57b19ee2-1401-4b3c-81c8-e01276f18a93
  parameters:
    backupTargetName: default
    dataEngine: v1
    dataLocality: disabled
    disableRevisionCounter: "true"
    fromBackup: ""
    fsType: ext4
    numberOfReplicas: "3"
    staleReplicaTimeout: "30"
    unmapMarkSnapChainRemoved: ignored
  provisioner: driver.longhorn.io
  reclaimPolicy: Delete
  volumeBindingMode: Immediate
- allowVolumeExpansion: true
  apiVersion: storage.k8s.io/v1
  kind: StorageClass
  metadata:
    creationTimestamp: "2025-11-20T10:29:31Z"
    name: longhorn-static
    resourceVersion: "3366160"
    uid: 8f14c882-cdd8-4697-8626-694834cd7a0a
  parameters:
    staleReplicaTimeout: "30"
  provisioner: driver.longhorn.io
  reclaimPolicy: Delete
  volumeBindingMode: Immediate
kind: List
metadata:
  resourceVersion: ""
