apiVersion: v1
items:
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    annotations:
      meta.helm.sh/release-name: monitoring
      meta.helm.sh/release-namespace: monitoring
    creationTimestamp: "2025-11-20T12:46:25Z"
    labels:
      app.kubernetes.io/instance: monitoring
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: grafana
      app.kubernetes.io/version: 12.3.0
      helm.sh/chart: grafana-10.1.5
    name: monitoring-grafana
    namespace: monitoring
    resourceVersion: "3388793"
    uid: 20902ead-afbd-435b-8640-5f3b080ab861
  rules: null
kind: List
metadata:
  resourceVersion: ""
