apiVersion: v1
items:
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    annotations:
      meta.helm.sh/release-name: monitoring
      meta.helm.sh/release-namespace: monitoring
    creationTimestamp: "2025-11-20T12:46:25Z"
    labels:
      app.kubernetes.io/instance: monitoring
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: grafana
      app.kubernetes.io/version: 12.3.0
      helm.sh/chart: grafana-10.1.5
    name: monitoring-grafana
    namespace: monitoring
    resourceVersion: "3388794"
    uid: 3f5b25a2-f82b-48e9-8eca-b9a9b9deb4f7
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: monitoring-grafana
  subjects:
  - kind: ServiceAccount
    name: monitoring-grafana
    namespace: monitoring
kind: List
metadata:
  resourceVersion: ""
