apiVersion: v1
items:
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    annotations:
      meta.helm.sh/release-name: longhorn
      meta.helm.sh/release-namespace: longhorn-system
    creationTimestamp: "2025-11-20T10:29:12Z"
    labels:
      app.kubernetes.io/instance: longhorn
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: longhorn
      app.kubernetes.io/version: v1.10.1
      helm.sh/chart: longhorn-1.10.1
    name: longhorn
    namespace: longhorn-system
    resourceVersion: "3365883"
    uid: bb335cd8-e2cc-4c4e-832c-ff08f900c007
  rules:
  - apiGroups:
    - ""
    resources:
    - pods
    - pods/log
    - events
    - secrets
    - services
    - endpoints
    - configmaps
    - serviceaccounts
    - persistentvolumeclaims
    - persistentvolumeclaims/status
    verbs:
    - '*'
  - apiGroups:
    - apps
    resources:
    - daemonsets
    - deployments
    - statefulsets
    - replicasets
    verbs:
    - '*'
  - apiGroups:
    - batch
    resources:
    - jobs
    - cronjobs
    verbs:
    - '*'
  - apiGroups:
    - policy
    resources:
    - poddisruptionbudgets
    verbs:
    - '*'
  - apiGroups:
    - coordination.k8s.io
    resources:
    - leases
    verbs:
    - '*'
  - apiGroups:
    - rbac.authorization.k8s.io
    resources:
    - roles
    - rolebindings
    verbs:
    - '*'
  - apiGroups:
    - discovery.k8s.io
    resources:
    - endpointslices
    verbs:
    - '*'
kind: List
metadata:
  resourceVersion: ""
